### ISSUE TITLE
`isSnapshot`, `isRC` providers compare equality of project version string versus a `SpecialStage` constant

### ISSUE THREAD

**Issue by bric3** [JavierSegoviaCordoba/semver-gradle-plugin#147]
Using the version providers introduced in JavierSegoviaCordoba/semver-gradle-plugin#93

I wonder if I'm using it right. Suppose the following task that emit the version 0.0.1-SNAPSHOT

```
./gradlew publish -Psemver.stage=snapshot
```

![image](https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/assets/803621/b8db2e04-e630-44a4-8200-ca36687081e6)

This call return `false`, because the comparison is performing an equality on the `String` representation of the version.

```
public val String.isSnapshot: Boolean
    get() = lowercase() == SpecialStage.snapshot
```

I was able to work around this with my own provider

```
val isSnapshot = providers.provider { GradleVersion(project.version.toString()).isSnapshot }
```

----

Gradle : 8.7
Semver : 0.5.0

**Comment by JavierSegoviaCordoba** [comment]
I will check, I think there is a lazy version too, but you need to cast the `version`.

Thank you for the report!

**Comment by JavierSegoviaCordoba** [comment]
Fixed here: https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/commit/e733267ecb8f5fdfa02d1179d207cd175221c4fd

**Comment by bric3** [comment]
Thanks
