### ISSUE TITLE
createSemverTag prints version

### ISSUE THREAD

**Issue by rivancic** [JavierSegoviaCordoba/semver-gradle-plugin#160]
Running createSemverTask doesn't create any tag it prints following.
![image](https://github.com/user-attachments/assets/25b5910e-b0a9-4164-bbfc-2b56652e7be6)

just running print task.

What am I doing wrong? I expect to create new tag.

**Comment by JavierSegoviaCordoba** [comment]
Hello 👋 

You need to provide the tag you want to upgrade the version.

As your project is using the tag `v`

```
./gradlew cST - P semver.tagPrefix=v
```

**Comment by rivancic** [comment]
It's working!

Again, if I set it already to project (semver.project.tagPrefix) I think this should be the default tag then later for any new version tag creation. Except if one would like to assign for specific reason different tag than project default then I would expect `semver.tagPrefix` to be set.

**Comment by JavierSegoviaCordoba** [comment]
The default tag prefix is a empty string, so if you don't want to specify anything I recommend you to remove the prefix.

The prefix is only necessary for multi module projects with different versions so you can upgrade one project without upgrading the other.

**Comment by rivancic** [comment]
Thanks for clarifying that up. Will have to use the prefix as its used in my project as a convention.

**Comment by JavierSegoviaCordoba** [comment]
You can add both properties to the root `gradle.properties` and forget about them 😄
