### ISSUE TITLE
Unable to get the correct tag prefix in configuration phase

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JavierSegoviaCordoba/semver-gradle-plugin#79]
It is a bad practice to use eager Gradle APIs, but due to some third-party plugins, sometimes it is necessary to get the tag prefix in the configuration phase.

The only way to fix this is using a Gradle Property, for example `semver.project.tagPrefix`, instead of getting the prefix from the plugin extension `semver.tagPrefix`.

**Comment by bric3** [comment]
Oh ok, that said I think the readme should really highlight it this way then (following your feedback):

> Tag prefix need to be configured. This can be done via the DSL
> ```Gradle Kotlin DSL
> semver {
>     tagPrefix = "v"
> }
> ```
>
> Or via this property if other part of the build query the version earlier.
> ```properties
> semver.project.tagPrefix=v
> ```
> 
> > [!CAUTION]
> > Do not confuse with `semver.tagPrefix` which is used to indicate which tag is getting bumped.
