### ISSUE TITLE
Since Gradle 7.0, `SNAPSHOT` is higher than `RC` stage.

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JavierSegoviaCordoba/semver-gradle-plugin#92]
Related info in this discussion https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/discussions/91

**Comment by bric3** [comment]
Since 7.0 ;)

**Comment by JavierSegoviaCordoba** [comment]
Fixed with https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/commit/b7504f478b15416250f3d45cb78d1b31080485a9

**Comment by JavierSegoviaCordoba** [comment]
@bric3 if you try [0.4.0-alpha.1](https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/releases/tag/0.4.0-alpha.1) it has this fix

**Comment by bric3** [comment]
Thanks it did solve the issue !
