### ISSUE TITLE
Adding some APIs

### ISSUE THREAD

**Issue by bric3** [JavierSegoviaCordoba/semver-gradle-plugin#93]
In my build script depending, I wrote some tasks that depends on the computed version, and some on the old version.

Typically choosing the repository to upload artifacts weather the version is a snapshot or a release (alpha, beta, rc, final). In another project I'm working on there's the concept of EAP (early access preview).
Currently I have created my own functions that parse the version. But it would be useful if the plugin could provide those.

E.g.

```kotlin
fun isSnapshot(version: Any) = version.toString().endsWith("-SNAPSHOT") 
        || version.toString().matches(Regex(".*\\.\\d+\\+[0-9a-f]+")) // .54+6a08d70
```

Another thing that I'm currently doing differently is getting the last tag (and possibly the commit id), which could be used to trigger some tasks.

**Comment by JavierSegoviaCordoba** [comment]
I am doing something similar to that but outside of semver plugin, in [Hubdle](https://github.com/JavierSegoviaCordoba/hubdle/) or [Gradle Extensions](https://github.com/JavierSegoviaCordoba/gradle-extensions).

There is a Gradle issue to transform `version: Any` to `version: Provider<Any>`, but personally I think they should avoid `Any` and use a specific and deterministic type, even if it is `String`.

We can add a `val Project.isSnapshot: Provider<Boolean>` getter, indeed I think I should refactor the one I have to return a `Provider`.

```kotlin
public val Project.isSnapshot: Boolean
    get() = version.toString().endsWith("-SNAPSHOT", ignoreCase = true)
```

Change to

```kotlin
public val Project.isSnapshot: Provider<Boolean>
    get() = provider { version.toString().endsWith("-SNAPSHOT", ignoreCase = true) }
```

And in semver plugin I could just expose it:

```kotlin
public val Project.isSnapshot: Provider<Boolean>
    get() = com.javiersc.gradle.extensions.project.isSnapshot
```

The reason to expose a `Provider` is to clearly indicate it should be consumed in tasks or lazy configurations and avoid getting its value in the configuration phase. Indeed, `version.toString()` is calling `get()` internally.

Additionally, we could add more for common values like `isAlpha`, `isBeta`, `isRC`, `isFinal` and so on.

**Comment by JavierSegoviaCordoba** [comment]
Fixed with https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/commit/0b8156d549f9bc29677c4a2349449ccd17342ccd

**Comment by JavierSegoviaCordoba** [comment]
Added those ones [isVersionExtension.kt](https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/blob/0b8156d549f9bc29677c4a2349449ccd17342ccd/semver-gradle-plugin/main/kotlin/com/javiersc/semver/gradle/plugin/extensions/isVersionExtensions.kt):

- `Project.isAlpha: Provider<Boolean>` extension
- `Project.isNotAlpha: Provider<Boolean>` extension
- `Project.isBeta: Provider<Boolean>` extension
- `Project.isNotBeta: Provider<Boolean>` extension
- `Project.isDev: Provider<Boolean>` extension
- `Project.isNotDev: Provider<Boolean>` extension
- `Project.isRC: Provider<Boolean>` extension
- `Project.isNotRC: Provider<Boolean>` extension
- `Project.isSnapshot: Provider<Boolean>` extension
- `Project.isNotSnapshot: Provider<Boolean>` extension

**Comment by bric3** [comment]
Ah cool ! 
I think the not variants like `isNotSnapshot` are not needed, as prefixing with `!` or using the `.not` postfix in kotlin should be enough.

Also what about the API about reading the previous git tag, since it's used to compute the current version.

**Comment by JavierSegoviaCordoba** [comment]
> Also what about the API about reading the previous git tag, since it's used to compute the current version.
> 
> Maybe also reading the commit hash of the related tag. And the current commit hash as a commodity (can be used to set an entry in the manifest).

How would you consume those values? in a lambda in the plugin extension for example?

**Comment by JavierSegoviaCordoba** [comment]
Maybe the semver extension can have a provider with those values which can be mapped to another task input/s.

What do you think?

**Comment by JavierSegoviaCordoba** [comment]
Fixed on https://github.com/JavierSegoviaCordoba/semver-gradle-plugin/commit/f63fd5ee13a8d8f28f10e1d620729b98e9598b39
