### ISSUE TITLE
`printSemver -q` outputs nothing

### ISSUE THREAD

**Issue by bric3** [JavierSegoviaCordoba/semver-gradle-plugin#94]
I believe this is because the task uses by default the gradle logger. I think this task should use a regular `println` instead.

**Comment by JavierSegoviaCordoba** [comment]
To be honest I am not an expert on logging. With this the `print` will not been shown, but is there no way to do that with the logger?

**Comment by JavierSegoviaCordoba** [comment]
The plugin uses `LIFECYCLE`, which is higher than quiet based on [the Gradle table](https://docs.gradle.org/current/userguide/logging.html#sec:choosing_a_log_level). So it looks like a bug

![image](https://user-images.githubusercontent.com/7463564/222972959-bf7462b9-6049-42c0-9856-1afdcc046d82.png)
